name: Render Map

on:
  push:
    paths:
      - "Station.json"
      - "Path.json"
  pull_request:
    paths:
      - "Station.json"
      - "Path.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'C1710/TrainCompany-tools'
          path: 'tools'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install matplotlib
        run: python -m pip install matplotlib
      - name: Render map
        run: python tools/plot.py
      - uses: actions/upload-artifact@v3
        with:
          name: map
          path: map_plot.svg
          retention-days: 2
  # comment:
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: map
  #         path: map.svg
  #     - uses: actions/github-script@v6
  #       with:
  #         script: |
  #           github.rest.issues.createComment({
  #             issue_number: context.issue.number,
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             body: 'Map: ![Map]()'
  #           })